### ISSUE TITLE
Another Uncaught TypeError: Cannot read property 'array' of undefined issue

### ISSUE THREAD

**Issue by MrBabadook** [bryik/aframe-controller-cursor-component#18]
Aframe 0.5.0
Vive controllers
When trying to use the component I get a "Cannot read property 'array' of undefined" and the scene doesn't load.

The errors are : 

`three.js:14957 Uncaught TypeError: Cannot read property 'array' of undefined
    at At.Object.assign.raycast (https://aframe.io/releases/0.5.0/aframe.min.js:113:14953)
    at Dn (https://aframe.io/releases/0.5.0/aframe.min.js:109:9054)
    at Dn (https://aframe.io/releases/0.5.0/aframe.min.js:109:9119)
    at Un.intersectObjects (https://aframe.io/releases/0.5.0/aframe.min.js:117:689)
    at i.tick (https://aframe.io/releases/0.5.0/aframe.min.js:181:1401)
    at https://aframe.io/releases/0.5.0/aframe.min.js:250:6254
    at Array.forEach (native)
    at HTMLElement.value (https://aframe.io/releases/0.5.0/aframe.min.js:250:6216)
    at HTMLElement.value (https://aframe.io/releases/0.5.0/aframe.min.js:250:6410)
    at HTMLElement.render (https://aframe.io/releases/0.5.0/aframe.min.js:369:132)
Object.assign.raycast @ three.js:14957
Dn @ three.js:39156
Dn @ three.js:39164
intersectObjects @ three.js:39233
tick @ raycaster.js:106
(anonymous) @ a-scene.js:450
value @ a-scene.js:448
value @ a-scene.js:472
(anonymous) @ bind.js:12
e @ a-scene.js:392
(anonymous) @ a-scene.js:377
module.exports.fireEvent @ index.js:96
(anonymous) @ a-node.js:222
value @ a-node.js:221
(anonymous) @ a-node.js:118`

and 

`three.js:14957 Uncaught TypeError: Cannot read property 'array' of undefined
    at At.Object.assign.raycast (https://aframe.io/releases/0.5.0/aframe.min.js:113:14953)
    at Dn (https://aframe.io/releases/0.5.0/aframe.min.js:109:9054)
    at Dn (https://aframe.io/releases/0.5.0/aframe.min.js:109:9119)
    at Un.intersectObjects (https://aframe.io/releases/0.5.0/aframe.min.js:117:689)
    at i.tick (https://aframe.io/releases/0.5.0/aframe.min.js:181:1401)
    at https://aframe.io/releases/0.5.0/aframe.min.js:250:6254
    at Array.forEach (native)
    at HTMLElement.value (https://aframe.io/releases/0.5.0/aframe.min.js:250:6216)
    at HTMLElement.value (https://aframe.io/releases/0.5.0/aframe.min.js:250:6410)
    at HTMLElement.render (https://aframe.io/releases/0.5.0/aframe.min.js:369:132)`

I noticed this has been reported before but was apparently resolved, however for me it is crashing on load. Code attached as `<a-entity vive-controls="hand: right" controller-cursor position="0 .5 -0.5" ></a-entity>`

**Comment by bryik** [comment]
I'm guessing this is the same as the [attributes.position issue](https://github.com/bryik/aframe-controller-cursor-component/issues/16).

It used to work on earlier versions, but broke at some point (not sure how). A fix was made in A-Frame core, so the component is working again (but only with master). I'll add a note to the readme.

You can acquire master builds from the [core A-Frame repo](https://github.com/aframevr/aframe/tree/master/dist).

**Comment by bryik** [comment]
If you get the same error with master, feel free to reopen/file a new issue.

**Comment by MrBabadook** [comment]
Will test and either respond here or open a new issue, thank you for your quick reply (and making this component in the first place)

**Comment by bryik** [comment]
np!

I should have added a warning to the readme a while ago :smile:

**Comment by ngokevin** [comment]
I think this was if trying to raycast against a model that is currently loading. master's controller cursor (`raycaster="showLine: true"`) does not have this issue since I think it waits for a mesh.

**Comment by bryik** [comment]
@ngokevin What I still don't understand is how the component broke "retroactively". Is it just race condition weirdness (i.e. the bug was there all along but the model loaded fast enough to avoid it)? What caused it to start happening reliably?

I have [a 0.5.0 CodePen](https://codepen.io/bryik/pen/BRMjxB) which definitely crashed at one point, but I just tried it and...no crash. Now I'm beginning to question my sanity.
